block-beta
  columns 6

  %% Semestre 1
  S1["S1"]
  CDI["CDI"]
  TMD["TMD"]
  AP["AP"]
  LSD["LSD"]
  Eltr["Eltr"]

  %% Semestre 2
  S2["S2"]
  ALGA["ALGA"]
  RC["RC"]
  MPP["MPP"]
  AC["AC"]
  LIC["LIC"]

  %% Semestre 3
  S3["S3"]
  PE["PE"]
  ISI["ISI"]
  AIA["AIA"]
  SO["SO"]
  PAW["PAW"]
  
  %% Semestre 4
  S4["S4"]
  FCD["FCD"]
  SisInf["SisInf"]
  PC["PC"]
  LAE["LAE"]
  LES["LES"]

  %% Semestre 5
  S5["S5"]
  O5a["O5a"]
  SegInf["SegInf"]
  DAM["DAM"]
  AIS["AIS"]
  ESW["ESW"]

  %% Semestre 6
  S6["S6"]
  O6a["O6a"]
  O6b["O6b"]
  PS["PS"]:3

  style S1 fill:none,stroke:none;
  style S2 fill:none,stroke:none;
  style S3 fill:none,stroke:none;
  style S4 fill:none,stroke:none;
  style S5 fill:none,stroke:none;
  style S6 fill:none,stroke:none; 

  style CDI  fill:#dac4f7,stroke:#a88bd9
  style TMD  fill:#dac4f7,stroke:#a88bd9
  style ALGA fill:#dac4f7,stroke:#a88bd9
  style PE   fill:#dac4f7,stroke:#a88bd9

  style RC   fill:#e9c6d2, stroke:#a1607f

  style Eltr fill:#b0e0ff,stroke:#1f6be1

  style LSD  fill:#d9e8ff,stroke:#7a9cd9
  style AC   fill:#d9e8ff,stroke:#7a9cd9

  style AIA  fill:#f0f2c9,stroke:#c4bc6d

  style PAW  fill:#ECEED2,stroke:#989882

  style SO   fill:#c8f0f2,stroke:#7bcdd1
  style AIS  fill:#c8f0f2,stroke:#7bcdd1

  style LAE  fill:#D0F4E2,stroke:#85CEAB
  style PC   fill:#D0F4E2,stroke:#85CEAB
  style ESW  fill:#D0F4E2,stroke:#85CEAB

  style AP   fill:#d8f7d1,stroke:#8ecf85
  style MPP  fill:#d8f7d1,stroke:#8ecf85
  style DAM  fill:#d8f7d1,stroke:#8ecf85

  style FCD  fill:#ffe3c2,stroke:#f0a958
  style ISI  fill:#fff1c9,stroke:#e5b95f
  style SisInf fill:#fff1c9,stroke:#e5b95f

  style SegInf fill:#f2d1c9,stroke:#b96a5f

  style LIC fill:#eee,stroke:#000,stroke-width:2px,font-weight:bold
  style LES fill:#eee,stroke:#000,stroke-width:2px,font-weight:bold
  style PS  fill:#eee,stroke:#000,stroke-width:2px,font-weight:bold
